import { LegalIdentity, LegalPage, legalMetadata } from "@/components/LegalPage";

export const metadata = legalMetadata("Privacy Policy", "Informativa sul trattamento dei dati personali dei visitatori e di chi richiede una valutazione ad ACCELERIAMO.", "/privacy-policy");

export default function PrivacyPolicy() {
  return <LegalPage title="Privacy Policy" path="/privacy-policy" intro="Come trattiamo i dati quando visiti il sito o ci chiedi una valutazione.">
    <section><h2>1. Titolare del trattamento</h2><LegalIdentity /><p>Questa informativa riguarda il sito acceleriamo.it e le richieste ricevute tramite il modulo di contatto e WhatsApp. È resa ai sensi dell’art. 13 del Regolamento (UE) 2016/679 (GDPR) e del D.lgs. 196/2003, come modificato dal D.lgs. 101/2018.</p></section>
    <section><h2>2. Dati che raccogliamo</h2><p>Il modulo richiede nome e cognome, azienda, numero di telefono, attività da valutare e, se lo indichi, una descrizione del processo attuale. L’email è facoltativa. Puoi aggiungere ruolo, numero di persone coinvolte, frequenza dell’attività e strumenti utilizzati. Riceviamo anche la versione dei documenti resa disponibile, la data di ricezione, un identificativo della richiesta e gli eventuali parametri della campagna (UTM) presenti nel collegamento da cui arrivi, per associare la richiesta alla sua provenienza. Se ci scrivi su WhatsApp riceviamo il numero e i contenuti che scegli di inviare.</p><p>La navigazione comporta la trasmissione di dati tecnici, quali indirizzo IP, URL richiesto, data e ora, informazioni sul browser ed esito della richiesta, che possono essere trattati dall’infrastruttura di hosting per erogare e proteggere il sito.</p><p>Descrivi il processo aziendale senza inserire dati sanitari, altre categorie particolari di dati, dati giudiziari, password o informazioni personali di clienti, dipendenti o terzi non necessarie.</p></section>
    <section><h2>3. Finalità e basi giuridiche</h2><ul>
      <li><strong>Valutare il caso e organizzare la consulenza:</strong> esaminare l’attività descritta, ricontattarti via email e telefono, fissare una consulenza ed eventualmente preparare una proposta. La base è l’esecuzione di misure precontrattuali richieste dall’interessato (art. 6, par. 1, lett. b, GDPR). Se agisci per un’azienda, il trattamento dei tuoi recapiti professionali si basa sul legittimo interesse a gestire la richiesta dell’azienda e le relative comunicazioni (lett. f).</li>
      <li><strong>Funzionamento, sicurezza e tutela dei diritti:</strong> prevenire abusi, documentare la richiesta e gestire eventuali contestazioni, sulla base del legittimo interesse a proteggere il servizio e i diritti del titolare (lett. f), nel rispetto dei diritti degli interessati.</li>
      <li><strong>Obblighi di legge:</strong> adempiere a richieste vincolanti delle autorità e agli obblighi applicabili (lett. c).</li>
    </ul><p>Per rispondere alla tua richiesta non chiediamo un consenso al marketing o l’accettazione di un contratto. Il modulo non iscrive a newsletter né avvia un incarico a pagamento.</p><p>Vercel Web Analytics misura le visite in forma aggregata, senza cookie, per comprendere l’utilizzo del sito. I parametri UTM inviati con la richiesta servono a identificarne la provenienza, sulla base del legittimo interesse a valutare i canali di contatto.</p><p>Se Meta Pixel è configurato, solo con il tuo consenso separato (art. 6, par. 1, lett. a, GDPR) misuriamo visite, clic su WhatsApp e richieste effettivamente ricevute. Quando è configurata anche l’API Conversioni, il server può inviare a Meta l’evento di richiesta, il relativo identificativo, telefono ed eventuale email sottoposti ad hash, identificatori pubblicitari disponibili e dati tecnici. L’hash non rende anonimi i dati: Meta può associarli ai propri utenti per attribuire e ottimizzare le campagne. Puoi rifiutare o revocare questa scelta dalle preferenze cookie senza impedire il contatto.</p></section>
    <section><h2>4. Conferimento dei dati</h2><p>I campi contrassegnati, compreso il numero di telefono, sono necessari per comprendere la richiesta e ricontattarti. Senza questi dati il modulo non può essere inviato. L’email e i dettagli aggiuntivi sono facoltativi e la loro omissione non impedisce di chiedere la valutazione. L’informativa è collegata sotto il pulsante di invio; non sono richieste caselle di accettazione.</p></section>
    <section><h2>5. Modalità e destinatari</h2><p>Le richieste sono inviate via email tramite il servizio di posta elettronica di Aruba e gestite dal titolare. Il sito non dispone di un database applicativo delle richieste. L’hosting e le statistiche aggregate sono forniti da Vercel. Per il tracciamento pubblicitario autorizzato i dati sono comunicati a Meta Platforms Ireland; per i messaggi WhatsApp si applicano anche le condizioni del relativo servizio. Possono accedere ai dati il titolare, le persone autorizzate e i fornitori necessari per hosting, posta elettronica e assistenza tecnica, nei limiti delle rispettive attività e, quando operano per conto del titolare, sulla base di accordi ai sensi dell’art. 28 GDPR. I dati non sono diffusi né venduti.</p><p>Le autorità e i consulenti possono ricevere i soli dati necessari quando previsto dalla legge o per la tutela di un diritto.</p></section>
    <section><h2>6. Conservazione</h2><p>Le richieste che non danno luogo a un incarico sono conservate per un massimo di 12 mesi dall’ultimo scambio relativo alla consulenza, poi cancellate o rese anonime. I parametri UTM e la versione dell’informativa associati seguono lo stesso termine. In caso di contestazione, i soli dati necessari possono essere conservati sino alla sua definizione e per i termini di tutela applicabili.</p><p>Se nasce un rapporto contrattuale, i dati necessari alla sua esecuzione e agli obblighi amministrativi sono trattati secondo l’informativa relativa all’incarico. I termini fiscali non si applicano automaticamente a tutte le richieste di contatto.</p><p>I dati tecnici sono conservati per il tempo necessario all’erogazione e alla sicurezza del servizio, secondo la configurazione dei fornitori. Eventuali dati relativi a incidenti sono conservati limitatamente alle esigenze di accertamento e tutela.</p></section>
    <section><h2>7. Fornitori e trasferimenti fuori dallo SEE</h2><p>La posta elettronica è erogata da Aruba S.p.A., con sede in Italia. I servizi di hosting, WhatsApp e, con consenso, misurazione Meta possono comportare il trattamento dei dati anche al di fuori dello Spazio economico europeo. Gli eventuali trasferimenti devono rispettare il capo V GDPR: decisioni di adeguatezza applicabili oppure clausole contrattuali standard e, quando necessarie, misure supplementari. Puoi chiedere al titolare l’elenco aggiornato dei destinatari e una copia delle garanzie applicabili.</p><p>Per informazioni generali sul servizio di posta consulta l’<a href="https://www.aruba.it/informativa.aspx" target="_blank" rel="noopener noreferrer">informativa privacy di Aruba</a>. L’informativa del fornitore non sostituisce quella del titolare per la gestione della tua richiesta.</p></section>
    <section><h2>8. I tuoi diritti</h2><p>Contattando il titolare ai recapiti sopra indicati puoi chiedere accesso, rettifica, cancellazione, limitazione e, nei casi previsti, portabilità dei dati. Puoi opporti ai trattamenti basati sul legittimo interesse per motivi legati alla tua situazione particolare. Qualora un trattamento si basi sul consenso, puoi revocarlo senza pregiudicare quanto effettuato prima della revoca.</p><p>Riceverai riscontro di regola entro un mese; un’eventuale proroga, fino a ulteriori due mesi nei casi previsti dal GDPR, sarà comunicata entro il primo mese con la motivazione. Puoi inoltre proporre reclamo al <a href="https://www.garanteprivacy.it/home/diritti/come-agire-per-tutelare-i-tuoi-dati-personali" target="_blank" rel="noopener noreferrer">Garante per la protezione dei dati personali</a> e ricorrere all’autorità giudiziaria.</p></section>
    <section><h2>AI WorkMap</h2><p>Per la conversazione AI, il profilo professionale e la consegna gratuita del documento PDF via email si applicano anche le <a href="/ai-workmap/condizioni#privacy">informazioni privacy specifiche di AI WorkMap</a>. Non viene effettuata un’iscrizione automatica a comunicazioni marketing.</p></section>
    <section><h2>9. Cookie e aggiornamenti</h2><p>Le informazioni sulle tecnologie utilizzate sono nella <a href="/cookie-policy">Cookie Policy</a>. La data in apertura identifica questa versione; eventuali nuovi trattamenti saranno accompagnati dall’aggiornamento dell’informativa e, quando necessario, da una comunicazione specifica.</p></section>
  </LegalPage>;
}
