import { LegalIdentity, LegalPage, legalMetadata } from "@/components/LegalPage";

export const metadata = legalMetadata("Privacy Policy", "Informativa sul trattamento dei dati personali dei visitatori e di chi richiede una consulenza ad ACCELERIAMO.", "/privacy-policy");

export default function PrivacyPolicy() {
  return <LegalPage title="Privacy Policy" path="/privacy-policy" intro="Come trattiamo i dati quando visiti il sito o ci chiedi una consulenza gratuita.">
    <section><h2>1. Titolare del trattamento</h2><LegalIdentity /><p>Questa informativa riguarda il sito acceleriamo.it e le richieste ricevute tramite il modulo di contatto. È resa ai sensi dell’art. 13 del Regolamento (UE) 2016/679 (GDPR) e del D.lgs. 196/2003, come modificato dal D.lgs. 101/2018.</p></section>
    <section><h2>2. Dati che raccogliamo</h2><p>Il modulo richiede nome e cognome, azienda, email di lavoro, problema da risolvere e descrizione del processo attuale. Puoi aggiungere ruolo, numero di persone coinvolte, frequenza dell’attività e strumenti utilizzati. Riceviamo anche la dichiarazione di lettura della privacy, l’accettazione dei termini, la versione dei documenti e la data di ricezione.</p><p>La navigazione comporta la trasmissione di dati tecnici, quali indirizzo IP, URL richiesto, data e ora, informazioni sul browser ed esito della richiesta, che possono essere trattati dall’infrastruttura di hosting per erogare e proteggere il sito.</p><p>Descrivi il processo aziendale senza inserire dati sanitari, altre categorie particolari di dati, dati giudiziari, password o informazioni personali di clienti, dipendenti o terzi non necessarie.</p></section>
    <section><h2>3. Finalità e basi giuridiche</h2><ul>
      <li><strong>Rispondere e organizzare la consulenza:</strong> valutare la richiesta, ricontattarti ed eventualmente preparare una proposta. La base è l’esecuzione di misure precontrattuali richieste dall’interessato (art. 6, par. 1, lett. b, GDPR). Se agisci per un’azienda, il trattamento dei tuoi recapiti professionali si basa sul legittimo interesse a gestire la richiesta dell’azienda e le relative comunicazioni (lett. f).</li>
      <li><strong>Funzionamento, sicurezza e tutela dei diritti:</strong> prevenire abusi, documentare la richiesta e gestire eventuali contestazioni, sulla base del legittimo interesse a proteggere il servizio e i diritti del titolare (lett. f), nel rispetto dei diritti degli interessati.</li>
      <li><strong>Obblighi di legge:</strong> adempiere a richieste vincolanti delle autorità e agli obblighi applicabili (lett. c).</li>
    </ul><p>La casella privacy documenta la presa visione dell’informativa: non è un consenso al marketing. Il modulo non iscrive a newsletter, non autorizza campagne promozionali e non comporta profilazione o decisioni esclusivamente automatizzate con effetti giuridici o analogamente significativi.</p></section>
    <section><h2>4. Conferimento dei dati</h2><p>I campi contrassegnati sono necessari per comprendere e gestire la richiesta. Senza questi dati il modulo non può essere inviato. I dettagli aggiuntivi sono facoltativi e la loro omissione non impedisce di chiedere la consulenza. Prima dell’invio sono richieste la presa visione della presente informativa e l’accettazione dei termini della richiesta gratuita.</p></section>
    <section><h2>5. Modalità e destinatari</h2><p>Le richieste sono inviate via email tramite il servizio Gmail di Google e gestite nella casella del titolare. Il sito non dispone di un database applicativo delle richieste. Possono accedere ai dati il titolare, le persone autorizzate e i fornitori necessari per hosting, posta elettronica e assistenza tecnica, nei limiti delle rispettive attività e, quando operano per conto del titolare, sulla base di accordi ai sensi dell’art. 28 GDPR. I dati non sono diffusi né venduti.</p><p>Le autorità e i consulenti possono ricevere i soli dati necessari quando previsto dalla legge o per la tutela di un diritto.</p></section>
    <section><h2>6. Conservazione</h2><p>Le richieste che non danno luogo a un incarico sono conservate per un massimo di 12 mesi dall’ultimo scambio relativo alla consulenza, poi cancellate o rese anonime. Le dichiarazioni associate seguono lo stesso termine. In caso di contestazione, i soli dati necessari possono essere conservati sino alla sua definizione e per i termini di tutela applicabili.</p><p>Se nasce un rapporto contrattuale, i dati necessari alla sua esecuzione e agli obblighi amministrativi sono trattati secondo l’informativa relativa all’incarico. I termini fiscali non si applicano automaticamente a tutte le richieste di contatto.</p><p>I dati tecnici sono conservati per il tempo necessario all’erogazione e alla sicurezza del servizio, secondo la configurazione dei fornitori. Eventuali dati relativi a incidenti sono conservati limitatamente alle esigenze di accertamento e tutela.</p></section>
    <section><h2>7. Fornitori e trasferimenti fuori dallo SEE</h2><p>I servizi di hosting e posta possono comportare il trattamento dei dati anche al di fuori dello Spazio economico europeo. Gli eventuali trasferimenti devono rispettare il capo V GDPR: decisioni di adeguatezza applicabili oppure clausole contrattuali standard e, quando necessarie, misure supplementari. Puoi chiedere al titolare l’elenco aggiornato dei destinatari e una copia delle garanzie applicabili.</p><p>Per informazioni generali sul servizio di posta consulta la <a href="https://policies.google.com/privacy?hl=it" target="_blank" rel="noopener noreferrer">privacy policy di Google</a>. L’informativa del fornitore non sostituisce quella del titolare per la gestione della tua richiesta.</p></section>
    <section><h2>8. I tuoi diritti</h2><p>Contattando il titolare ai recapiti sopra indicati puoi chiedere accesso, rettifica, cancellazione, limitazione e, nei casi previsti, portabilità dei dati. Puoi opporti ai trattamenti basati sul legittimo interesse per motivi legati alla tua situazione particolare. Qualora un trattamento si basi sul consenso, puoi revocarlo senza pregiudicare quanto effettuato prima della revoca.</p><p>Riceverai riscontro di regola entro un mese; un’eventuale proroga, fino a ulteriori due mesi nei casi previsti dal GDPR, sarà comunicata entro il primo mese con la motivazione. Puoi inoltre proporre reclamo al <a href="https://www.garanteprivacy.it/home/diritti/come-agire-per-tutelare-i-tuoi-dati-personali" target="_blank" rel="noopener noreferrer">Garante per la protezione dei dati personali</a> e ricorrere all’autorità giudiziaria.</p></section>
    <section><h2>9. Cookie e aggiornamenti</h2><p>Le informazioni sulle tecnologie utilizzate sono nella <a href="/cookie-policy">Cookie Policy</a>. La data in apertura identifica questa versione; eventuali nuovi trattamenti saranno accompagnati dall’aggiornamento dell’informativa e, quando necessario, da una comunicazione specifica.</p></section>
  </LegalPage>;
}
