import { LegalIdentity, LegalPage, legalMetadata } from "@/components/LegalPage";

export const metadata = legalMetadata("Termini e condizioni", "Condizioni di utilizzo del sito ACCELERIAMO e della richiesta di consulenza gratuita.", "/termini-e-condizioni");

export default function Terms() {
  return <LegalPage title="Termini e condizioni" path="/termini-e-condizioni" intro="Le condizioni per utilizzare il sito e richiedere una prima consulenza gratuita.">
    <section><h2>1. Gestore e informazioni legali</h2><LegalIdentity /><p>ACCELERIAMO è il nome con cui Diego Simoncini presenta i propri servizi di consulenza, automazione e sviluppo software. Queste informazioni identificano il gestore anche ai fini dell’art. 7 D.lgs. 70/2003.</p></section>
    <section><h2>2. Oggetto del sito</h2><p>Il sito presenta servizi rivolti principalmente ad aziende e professionisti e permette di richiedere un primo confronto sul proprio caso. Non consente di acquistare servizi o effettuare pagamenti online. Gli esempi illustrano possibili applicazioni e non costituiscono promesse di risultati, risparmi o tempi di realizzazione per ogni progetto.</p></section>
    <section><h2>3. Richiesta di consulenza gratuita</h2><p>Inviando il modulo chiedi di essere ricontattato per valutare il problema descritto e concordare un primo incontro. La richiesta e il primo confronto sono gratuiti e non comportano obblighi di acquisto, abbonamenti o l’avvio di un incarico a pagamento.</p><p>La conferma di ricezione non equivale alla prenotazione di un appuntamento: disponibilità e modalità del confronto sono concordate successivamente. La valutazione iniziale dipende dalle informazioni fornite e non include automaticamente analisi tecniche complete, sviluppo o consegna di software.</p></section>
    <section><h2>4. Eventuali incarichi successivi</h2><p>Attività a pagamento, sviluppo, assistenza e manutenzione richiedono una proposta e un accordo separati, con oggetto, corrispettivi e imposte applicabili, tempi, responsabilità, diritti sul software e condizioni del servizio. L’accettazione di questi termini non sostituisce tale accordo.</p><p>Se l’incarico comporta trattamento di dati per conto del cliente, i ruoli e gli eventuali accordi privacy saranno definiti prima dell’accesso a tali dati.</p></section>
    <section><h2>5. Uso corretto e informazioni inviate</h2><p>Fornisci recapiti corretti e informazioni che sei autorizzato a comunicare. Non utilizzare il modulo per spam, contenuti illeciti, credenziali, segreti aziendali o dati personali di terzi non necessari. Non sono consentiti tentativi di compromettere la sicurezza o la disponibilità del sito.</p><p>L’invio di una descrizione non trasferisce al gestore diritti sui tuoi materiali e non costituisce di per sé un accordo di riservatezza specifico. Prima di condividere documentazione riservata, concorda modalità e tutele con il titolare.</p></section>
    <section><h2>6. Contenuti e proprietà intellettuale</h2><p>Testi, grafica, marchi e altri materiali del sito appartengono al gestore o ai rispettivi titolari. È consentita la consultazione per valutare i servizi e la condivisione dei collegamenti. Riproduzioni o utilizzi ulteriori richiedono autorizzazione, salvo quanto consentito dalla legge.</p></section>
    <section><h2>7. Disponibilità e responsabilità</h2><p>Il gestore cura l’aggiornamento del sito, che può subire interruzioni per manutenzione o problemi tecnici. In caso di errore nell’invio, il modulo lo segnala e la richiesta deve essere ripetuta. Eventuali collegamenti esterni rimandano a servizi gestiti dai rispettivi soggetti.</p><p>Restano ferme le responsabilità previste dalla legge, incluse quelle per dolo o colpa grave, e le tutele inderogabili degli utenti. Questi termini non limitano tali diritti.</p></section>
    <section><h2>8. Dati personali</h2><p>Il trattamento dei dati è descritto nella <a href="/privacy-policy">Privacy Policy</a>; le tecnologie del sito sono descritte nella <a href="/cookie-policy">Cookie Policy</a>. L’accettazione dei presenti termini non autorizza l’invio di marketing.</p></section>
    <section><h2>9. Legge applicabile e controversie</h2><p>Si applica la legge italiana, ferme le norme inderogabili applicabili. Per richieste o contestazioni puoi contattare il gestore ai recapiti indicati sopra. La competenza giudiziaria è determinata dalla legge; se agisci come consumatore restano salvi i diritti del Codice del consumo (D.lgs. 206/2005), compreso il foro del consumatore ove applicabile.</p></section>
    <section><h2>10. Versione e aggiornamenti</h2><p>Puoi salvare o stampare questa pagina con le funzioni del browser. La versione applicabile alla tua richiesta è quella disponibile al momento dell’invio, registrata insieme alla dichiarazione di accettazione. Le modifiche successive non si applicano retroattivamente alla richiesta già inviata.</p></section>
  </LegalPage>;
}
