import { LegalIdentity, LegalPage, legalMetadata } from "@/components/LegalPage";
import { CookiePreferences } from "@/components/MarketingConsent";

export const metadata = legalMetadata("Cookie Policy", "Informazioni su cookie, statistiche Vercel e misurazione delle campagne Meta di ACCELERIAMO.", "/cookie-policy");

export default function CookiePolicy() {
  return <LegalPage title="Cookie Policy" path="/cookie-policy" intro="Le tecnologie utilizzate dal sito e le tue possibilità di controllo.">
    <section><h2>1. Chi gestisce il sito</h2><LegalIdentity /><p>Questa informativa integra la <a href="/privacy-policy">Privacy Policy</a> e riguarda cookie e altri strumenti di tracciamento.</p></section>
    <section><h2>2. Funzioni del sito e statistiche</h2><p>Immagini e font sono serviti dal sito. Il modulo invia i dati al nostro server e non richiede cookie pubblicitari. I collegamenti a WhatsApp e LinkedIn aprono servizi esterni solo quando li selezioni.</p><p>Usiamo <a href="https://vercel.com/docs/analytics/privacy-policy" target="_blank" rel="noopener noreferrer">Vercel Web Analytics</a> per statistiche aggregate sull’utilizzo del sito: non usa cookie e non conserva identificatori che permettono di seguire la navigazione tra giorni o siti diversi. Le richieste tecniche all’hosting sono descritte nella Privacy Policy.</p><p>I parametri UTM eventualmente presenti nell’indirizzo della pagina vengono allegati alla richiesta di valutazione. Non vengono salvati dal sito in cookie, localStorage o sessionStorage.</p></section>
    <section><h2>3. Misurazione delle campagne Meta</h2><p>Quando configurato, Meta Pixel viene caricato solo dopo il tuo consenso. Misura la visita della pagina, il clic su WhatsApp (WhatsAppClick) e la richiesta di valutazione (Lead). Un clic su WhatsApp non dimostra che sia stato inviato un messaggio; Lead viene registrato solo dopo la conferma di ricezione del server.</p><p>Se configurata, l’API Conversioni invia dal server a Meta lo stesso evento Lead, con il medesimo identificativo per evitare conteggi doppi, e i dati descritti nella Privacy Policy. Anche questo invio richiede il consenso alla misurazione Meta. Il tracciamento automatico senza codice è disabilitato nel Pixel del sito.</p><p>Meta può utilizzare i dati per attribuire i contatti agli annunci, ottimizzare le campagne e associarli ai propri utenti. Consulta le informative <a href="https://www.facebook.com/privacy/policy/" target="_blank" rel="noopener noreferrer">privacy</a> e <a href="https://www.facebook.com/privacy/policies/cookies/" target="_blank" rel="noopener noreferrer">cookie di Meta</a>.</p></section>
    <section><h2>4. Cookie e durata</h2><ul>
      <li><strong>acceleriamo_marketing:</strong> cookie tecnico del sito, memorizza accettazione o rifiuto per 180 giorni. Non richiede consenso e viene scritto quando esprimi la scelta.</li>
      <li><strong>_fbp:</strong> cookie di Meta Pixel per la misurazione pubblicitaria, fino a 90 giorni; utilizzato solo con consenso.</li>
      <li><strong>_fbc:</strong> cookie di attribuzione del clic su un annuncio Meta, fino a 90 giorni, quando disponibile; utilizzato solo con consenso.</li>
    </ul><p>Meta può aggiornare questi strumenti secondo la propria policy. Il sito non carica Meta Pixel se manca la configurazione o se non hai accettato.</p></section>
    <section><h2>5. Accettazione, rifiuto e revoca</h2><p>Quando la misurazione Meta è configurata, il banner offre Accetta e Rifiuta. Nessun tracciamento pubblicitario parte prima della scelta; scorrere la pagina non equivale ad accettare. Puoi riaprire le preferenze dal footer o dal pulsante qui sotto e rifiutare anche dopo aver accettato. La revoca blocca gli eventi successivi e rimuove i cookie Meta accessibili a questo sito; non annulla i trattamenti già effettuati.</p><CookiePreferences /><p>Puoi inoltre eliminare i dati dalle impostazioni del browser. La scelta scade dopo 180 giorni; dopo la cancellazione del relativo cookie il banner viene mostrato nuovamente. Per approfondire: <a href="https://www.garanteprivacy.it/faq/cookie" target="_blank" rel="noopener noreferrer">FAQ del Garante sui cookie</a>.</p></section>
    <section><h2>6. Contatti e diritti</h2><p>Per informazioni e per esercitare i tuoi diritti utilizza i recapiti del titolare e le modalità indicate nella <a href="/privacy-policy">Privacy Policy</a>.</p></section>
  <section><h2>Ripresa della conversazione AI WorkMap</h2><p>Il cookie tecnico acceleriamo_workmap mantiene l’accesso alla conversazione e al documento privato, con durata massima di un anno. Non contiene le risposte della chat ed è accessibile solo al server. Si attiva quando avvii o riprendi l’analisi.</p></section>
  </LegalPage>;
}
