import { LegalIdentity, LegalPage, legalMetadata } from "@/components/LegalPage";

export const metadata = legalMetadata("Cookie Policy", "Informazioni su cookie, strumenti di tracciamento e tecnologie del sito ACCELERIAMO.", "/cookie-policy");

export default function CookiePolicy() {
  return <LegalPage title="Cookie Policy" path="/cookie-policy" intro="Le tecnologie utilizzate dal sito e le tue possibilità di controllo.">
    <section><h2>1. Chi gestisce il sito</h2><LegalIdentity /><p>Questa informativa integra la <a href="/privacy-policy">Privacy Policy</a> e riguarda cookie e altri strumenti di archiviazione o accesso al dispositivo, ai sensi dell’art. 122 D.lgs. 196/2003 e delle Linee guida del Garante del 10 giugno 2021.</p></section>
    <section><h2>2. Cosa sono i cookie</h2><p>I cookie sono piccoli file che un sito può memorizzare sul dispositivo. Alcuni servono a erogare funzionalità richieste o garantire sicurezza; altri misurano la navigazione o consentono pubblicità personalizzata. Anche strumenti diversi dai cookie possono memorizzare informazioni o tracciare gli utenti.</p></section>
    <section><h2>3. Tecnologie presenti</h2><p>Il sito non integra cookie di profilazione, pixel pubblicitari, servizi di analytics o strumenti di fingerprinting. Il codice applicativo non imposta cookie e non utilizza localStorage o sessionStorage per conservare dati dei visitatori.</p><ul><li><strong>Immagini e caratteri:</strong> sono serviti dal sito, senza caricamento di font da Google Fonts o altre piattaforme esterne.</li><li><strong>Modulo di contatto:</strong> invia i dati al server del sito e non richiede cookie. L’invio della mail tramite Google avviene sul server e non incorpora Gmail nel browser.</li><li><strong>Animazioni e menu:</strong> funzionano nel browser senza salvare un profilo di navigazione.</li><li><strong>Collegamenti esterni:</strong> le pagine dei siti collegati si aprono solo quando scegli di visitarli; si applicano le informative dei rispettivi gestori.</li></ul><p>I log tecnici delle richieste, descritti nella Privacy Policy, sono distinti dai cookie.</p></section>
    <section><h2>4. Perché non compare un banner</h2><p>Non essendo presenti strumenti di tracciamento che richiedono consenso, il sito non mostra un banner di accettazione. Secondo le <a href="https://www.garanteprivacy.it/faq/cookie" target="_blank" rel="noopener noreferrer">FAQ del Garante</a>, i cookie strettamente tecnici non richiedono consenso preventivo, ma devono essere descritti nell’informativa.</p><p>Se saranno introdotti strumenti non necessari, questa pagina sarà aggiornata e tali strumenti resteranno disattivati fino alla scelta dell’utente. Saranno disponibili il rifiuto e la successiva revoca del consenso con modalità semplici.</p></section>
    <section><h2>5. Controlli del browser</h2><p>Puoi verificare i dati dei siti, cancellarli o limitarne la memorizzazione nelle impostazioni di privacy del browser. Il blocco di tecnologie necessarie può influire sul funzionamento di alcuni servizi. Su questo sito non ci sono attualmente preferenze di profilazione da modificare.</p></section>
    <section><h2>6. Contatti e diritti</h2><p>Per informazioni sul trattamento e per esercitare i tuoi diritti utilizza i recapiti del titolare e le modalità indicate nella <a href="/privacy-policy">Privacy Policy</a>.</p></section>
  </LegalPage>;
}
